---
- name: Install bower components
  apt: update_cache=yes

- name: Ensure dependencies are installed
  apt: "pkg={{ item }} state=present"
  with_items:
    - nodejs-legacy
    - npm

- name: Install bower
  npm: name=bower global=yes

- name: Bower install components
  become: no
  bower: path=/vagrant/resources/sass
