---
# config/provision.yml
# Provision development environment

- name: Apply common configuration
  hosts: all
  become: yes
  roles:
    - common

- name: Setup app server
  hosts:
    - application
  become: yes
  roles:
    - java
    - lein
    - boot
